import { sql } from './db';

export type ContactStatus = 'new' | 'handled';
export type NewsletterStatus = 'active' | 'unsubscribed';

export type ContactRequest = {
  id: number;
  created_at: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  message: string | null;
  source_url: string | null;
  status: ContactStatus;
};

export type NewsletterSubscriber = {
  id: number;
  created_at: string;
  updated_at: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  status: NewsletterStatus;
};

let schemaReady = false;

export async function ensureLeadsSchema() {
  if (schemaReady) return;

  await sql`
    CREATE TABLE IF NOT EXISTS public.contact_requests (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
      first_name TEXT NOT NULL,
      last_name TEXT NOT NULL,
      email TEXT NOT NULL,
      phone TEXT,
      message TEXT,
      source_url TEXT,
      status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'handled'))
    )
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS idx_contact_requests_created_at
    ON public.contact_requests (created_at DESC)
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS idx_contact_requests_status
    ON public.contact_requests (status)
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
      updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
      email TEXT NOT NULL UNIQUE,
      first_name TEXT,
      last_name TEXT,
      status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed'))
    )
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_created_at
    ON public.newsletter_subscribers (created_at DESC)
  `;

  schemaReady = true;
}

export async function saveContactRequest(input: {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  message?: string;
  sourceUrl?: string;
}): Promise<ContactRequest> {
  await ensureLeadsSchema();
  const rows = await sql`
    INSERT INTO contact_requests (first_name, last_name, email, phone, message, source_url)
    VALUES (
      ${input.firstName},
      ${input.lastName},
      ${input.email.toLowerCase()},
      ${input.phone || null},
      ${input.message || null},
      ${input.sourceUrl || null}
    )
    RETURNING *
  `;
  return rows[0] as ContactRequest;
}

export async function listContactRequests(): Promise<ContactRequest[]> {
  await ensureLeadsSchema();
  const rows = await sql`
    SELECT * FROM contact_requests
    ORDER BY created_at DESC
    LIMIT 300
  `;
  return rows as unknown as ContactRequest[];
}

export async function setContactStatus(id: number, status: ContactStatus): Promise<boolean> {
  await ensureLeadsSchema();
  const rows = await sql`
    UPDATE contact_requests
    SET status = ${status}
    WHERE id = ${id}
    RETURNING id
  `;
  return rows.length > 0;
}

export async function deleteContactRequest(id: number): Promise<boolean> {
  await ensureLeadsSchema();
  const rows = await sql`
    DELETE FROM contact_requests WHERE id = ${id} RETURNING id
  `;
  return rows.length > 0;
}

export async function subscribeNewsletter(input: {
  email: string;
  firstName?: string;
  lastName?: string;
}): Promise<{ subscriber: NewsletterSubscriber; created: boolean }> {
  await ensureLeadsSchema();
  const email = input.email.toLowerCase();
  const existing = await sql`
    SELECT id FROM newsletter_subscribers WHERE email = ${email} LIMIT 1
  `;

  if (existing.length > 0) {
    return { subscriber: await updateNewsletterSubscriber(email, input.firstName, input.lastName), created: false };
  }

  try {
    const rows = await sql`
      INSERT INTO newsletter_subscribers (email, first_name, last_name)
      VALUES (${email}, ${input.firstName || null}, ${input.lastName || null})
      RETURNING *
    `;
    return { subscriber: rows[0] as NewsletterSubscriber, created: true };
  } catch (error) {
    const code = (error as { code?: string })?.code;
    if (code !== '23505') throw error;
    return { subscriber: await updateNewsletterSubscriber(email, input.firstName, input.lastName), created: false };
  }
}

async function updateNewsletterSubscriber(
  email: string,
  firstName?: string,
  lastName?: string,
): Promise<NewsletterSubscriber> {
  const rows = await sql`
    UPDATE newsletter_subscribers
    SET
      first_name = ${firstName || null},
      last_name = ${lastName || null},
      status = 'active',
      updated_at = TIMEZONE('utc'::text, NOW())
    WHERE email = ${email}
    RETURNING *
  `;
  return rows[0] as NewsletterSubscriber;
}

export async function listNewsletterSubscribers(): Promise<NewsletterSubscriber[]> {
  await ensureLeadsSchema();
  const rows = await sql`
    SELECT * FROM newsletter_subscribers
    ORDER BY created_at DESC
    LIMIT 500
  `;
  return rows as unknown as NewsletterSubscriber[];
}

export async function setNewsletterStatus(id: number, status: NewsletterStatus): Promise<boolean> {
  await ensureLeadsSchema();
  const rows = await sql`
    UPDATE newsletter_subscribers
    SET status = ${status}, updated_at = TIMEZONE('utc'::text, NOW())
    WHERE id = ${id}
    RETURNING id
  `;
  return rows.length > 0;
}

export async function deleteNewsletterSubscriber(id: number): Promise<boolean> {
  await ensureLeadsSchema();
  const rows = await sql`
    DELETE FROM newsletter_subscribers WHERE id = ${id} RETURNING id
  `;
  return rows.length > 0;
}
