-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Articles Table
create table public.articles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  author text,
  cover_image text,
  excerpt text,
  content text,
  tags text[]
);

-- Events Table
create table public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  date timestamp with time zone,
  time text,
  location text,
  cover_image text,
  description text,
  price text,
  status text check (status in ('upcoming', 'past')),
  tags text[]
);

-- Storage Bucket for Images
insert into storage.buckets (id, name, public) values ('images', 'images', true);

-- Security Policies (RLS)

-- Enable RLS
alter table public.articles enable row level security;
alter table public.events enable row level security;

-- Policies for Articles
-- Everyone can read published articles
create policy "Public articles are viewable by everyone"
  on public.articles for select
  using (true);

-- Only authenticated users can insert/update/delete (Admin)
create policy "Authenticated users can insert articles"
  on public.articles for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update articles"
  on public.articles for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete articles"
  on public.articles for delete
  using (auth.role() = 'authenticated');

-- Policies for Events
-- Everyone can read events
create policy "Public events are viewable by everyone"
  on public.events for select
  using (true);

-- Only authenticated users can insert/update/delete (Admin)
create policy "Authenticated users can insert events"
  on public.events for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update events"
  on public.events for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete events"
  on public.events for delete
  using (auth.role() = 'authenticated');

-- Storage Policies
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'images' );

create policy "Authenticated users can upload"
  on storage.objects for insert
  with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

create policy "Authenticated users can update"
  on storage.objects for update
  using ( bucket_id = 'images' and auth.role() = 'authenticated' );

create policy "Authenticated users can delete"
  on storage.objects for delete
  using ( bucket_id = 'images' and auth.role() = 'authenticated' );
