-- Testimonials Table for General Site Reviews
-- These are different from article comments - they're general testimonials about the consultant
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  author_name text not null,
  author_role text, -- Optional: e.g., "Cliente dal 2015"
  quote text not null,
  rating integer check (rating >= 1 and rating <= 5),
  is_published boolean default false, -- Admin must approve before showing on site
  featured boolean default false, -- Highlight on homepage
  display_order integer default 0 -- For manual sorting
);

-- Create index for faster queries
create index if not exists testimonials_published_idx on public.testimonials(is_published, display_order);
create index if not exists testimonials_featured_idx on public.testimonials(featured);

-- Enable RLS
alter table public.testimonials enable row level security;

-- Policies for Testimonials
-- Everyone can read published testimonials
create policy "Published testimonials are viewable by everyone"
  on public.testimonials for select
  using (is_published = true);

-- Authenticated users (admin) can view all testimonials
create policy "Authenticated users can view all testimonials"
  on public.testimonials for select
  using (auth.role() = 'authenticated');

-- Everyone can insert testimonials (but they start unpublished for moderation)
create policy "Anyone can submit testimonials"
  on public.testimonials for insert
  with check (true);

-- Only authenticated users can update testimonials (admin panel)
create policy "Authenticated users can update testimonials"
  on public.testimonials for update
  using (true); -- In production, restrict this to service_role or specific admin role

-- Only authenticated users can delete testimonials
create policy "Authenticated users can delete testimonials"
  on public.testimonials for delete
  using (true); -- In production, restrict this to service_role or specific admin role

-- Function to update updated_at timestamp
create or replace function update_testimonials_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Trigger to automatically update updated_at
drop trigger if exists testimonials_updated_at on public.testimonials;
create trigger testimonials_updated_at
  before update on public.testimonials
  for each row
  execute function update_testimonials_updated_at();
