-- Comments Table for Articles
create table public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  article_slug text not null references public.articles(slug) on delete cascade,
  user_name text not null,
  rating integer check (rating >= 1 and rating <= 5),
  content text not null
);

-- Event RSVPs Table
create table public.event_rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_slug text not null references public.events(slug) on delete cascade,
  user_name text, -- Made optional or used for fallback
  user_email text, -- Added email field
  status text check (status in ('attending', 'not_attending'))
);

-- Enable RLS
alter table public.comments enable row level security;
alter table public.event_rsvps enable row level security;

-- Policies for Comments
-- Everyone can read comments
create policy "Public comments are viewable by everyone"
  on public.comments for select
  using (true);

-- Everyone can insert comments (for now, maybe add captcha later)
create policy "Public can insert comments"
  on public.comments for insert
  with check (true);

-- Allow deletion of comments (Warning: Publicly accessible)
create policy "Public can delete comments"
  on public.comments for delete
  using (true);

-- Policies for RSVPs
-- Everyone can read RSVPs (to show counts)
create policy "Public RSVPs are viewable by everyone"
  on public.event_rsvps for select
  using (true);

-- Everyone can insert RSVPs
create policy "Public can insert RSVPs"
  on public.event_rsvps for insert
  with check (true);

-- Allow deletion of RSVPs (Warning: Publicly accessible)
create policy "Public can delete RSVPs"
  on public.event_rsvps for delete
  using (true);

-- View for Article Stats (Average Rating)
create or replace view public.article_stats as
select
  article_slug,
  count(*) as comment_count,
  avg(rating)::numeric(3,2) as average_rating
from public.comments
group by article_slug;

-- View for Event Stats (RSVP Counts)
create or replace view public.event_stats as
select
  event_slug,
  count(*) filter (where status = 'attending') as attending_count,
  count(*) filter (where status = 'not_attending') as not_attending_count
from public.event_rsvps
group by event_slug;
