-- =============================================
-- SERGIO CONTEGIACOMO - SCHEMA COMPLETO SUPABASE
-- Esegui questo SQL nel SQL Editor di Supabase
-- per ricreare tutte le tabelle del progetto
-- =============================================
-- Data: 6 Dicembre 2025
-- =============================================

-- Abilita estensioni necessarie
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- PARTE 1: TABELLE PRINCIPALI
-- =============================================

-- Tabella Articles (Blog)
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  published_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  author TEXT,
  cover_image TEXT,
  excerpt TEXT,
  content TEXT,
  tags TEXT[]
);

-- Tabella Events
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  date TIMESTAMPTZ,
  time TEXT,
  location TEXT,
  cover_image TEXT,
  pdf_url TEXT,
  description TEXT,
  price TEXT,
  status TEXT CHECK (status IN ('upcoming', 'past')),
  tags TEXT[]
);

-- Tabella Comments (Commenti agli articoli)
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  article_slug TEXT NOT NULL REFERENCES public.articles(slug) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  content TEXT NOT NULL
);

-- Tabella Event RSVPs (Iscrizioni eventi)
CREATE TABLE IF NOT EXISTS public.event_rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  event_slug TEXT NOT NULL REFERENCES public.events(slug) ON DELETE CASCADE,
  user_name TEXT,
  user_email TEXT,
  status TEXT CHECK (status IN ('attending', 'not_attending'))
);

-- Tabella AudioPillole
CREATE TABLE IF NOT EXISTS public.audio_pillole (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  duration TEXT,
  published_at DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabella Press (Rassegna Stampa)
CREATE TABLE IF NOT EXISTS public.press (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  testata TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  published_at DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- PARTE 2: INDICI PER PERFORMANCE
-- =============================================

CREATE INDEX IF NOT EXISTS idx_articles_slug ON public.articles(slug);
CREATE INDEX IF NOT EXISTS idx_articles_published_at ON public.articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_slug ON public.events(slug);
CREATE INDEX IF NOT EXISTS idx_events_date ON public.events(date DESC);
CREATE INDEX IF NOT EXISTS idx_comments_article_slug ON public.comments(article_slug);
CREATE INDEX IF NOT EXISTS idx_event_rsvps_event_slug ON public.event_rsvps(event_slug);
CREATE INDEX IF NOT EXISTS idx_audio_pillole_published_at ON public.audio_pillole(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_press_published_at ON public.press(published_at DESC);

-- =============================================
-- PARTE 3: VIEWS (Statistiche)
-- =============================================

-- View per statistiche articoli
CREATE OR REPLACE VIEW public.article_stats AS
SELECT
  article_slug,
  COUNT(*) AS comment_count,
  AVG(rating)::NUMERIC(3,2) AS average_rating
FROM public.comments
GROUP BY article_slug;

-- View per statistiche eventi
CREATE OR REPLACE VIEW public.event_stats AS
SELECT
  event_slug,
  COUNT(*) FILTER (WHERE status = 'attending') AS attending_count,
  COUNT(*) FILTER (WHERE status = 'not_attending') AS not_attending_count
FROM public.event_rsvps
GROUP BY event_slug;

-- =============================================
-- PARTE 4: ROW LEVEL SECURITY (RLS)
-- =============================================

-- Abilita RLS su tutte le tabelle
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_rsvps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audio_pillole ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.press ENABLE ROW LEVEL SECURITY;

-- =============================================
-- PARTE 5: POLICIES - ARTICLES
-- =============================================

-- Drop existing policies (se esistono)
DROP POLICY IF EXISTS "Public articles are viewable by everyone" ON public.articles;
DROP POLICY IF EXISTS "Authenticated users can insert articles" ON public.articles;
DROP POLICY IF EXISTS "Authenticated users can update articles" ON public.articles;
DROP POLICY IF EXISTS "Authenticated users can delete articles" ON public.articles;

-- Lettura pubblica
CREATE POLICY "Public articles are viewable by everyone"
  ON public.articles FOR SELECT
  USING (true);

-- Scrittura solo per utenti autenticati
CREATE POLICY "Authenticated users can insert articles"
  ON public.articles FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update articles"
  ON public.articles FOR UPDATE
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete articles"
  ON public.articles FOR DELETE
  USING (auth.role() = 'authenticated');

-- =============================================
-- PARTE 6: POLICIES - EVENTS
-- =============================================

DROP POLICY IF EXISTS "Public events are viewable by everyone" ON public.events;
DROP POLICY IF EXISTS "Authenticated users can insert events" ON public.events;
DROP POLICY IF EXISTS "Authenticated users can update events" ON public.events;
DROP POLICY IF EXISTS "Authenticated users can delete events" ON public.events;

CREATE POLICY "Public events are viewable by everyone"
  ON public.events FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert events"
  ON public.events FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update events"
  ON public.events FOR UPDATE
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete events"
  ON public.events FOR DELETE
  USING (auth.role() = 'authenticated');

-- =============================================
-- PARTE 7: POLICIES - COMMENTS
-- =============================================

DROP POLICY IF EXISTS "Public comments are viewable by everyone" ON public.comments;
DROP POLICY IF EXISTS "Public can insert comments" ON public.comments;
DROP POLICY IF EXISTS "Public can delete comments" ON public.comments;

CREATE POLICY "Public comments are viewable by everyone"
  ON public.comments FOR SELECT
  USING (true);

CREATE POLICY "Public can insert comments"
  ON public.comments FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Authenticated can delete comments"
  ON public.comments FOR DELETE
  USING (auth.role() = 'authenticated');

-- =============================================
-- PARTE 8: POLICIES - EVENT RSVPS
-- =============================================

DROP POLICY IF EXISTS "Public RSVPs are viewable by everyone" ON public.event_rsvps;
DROP POLICY IF EXISTS "Public can insert RSVPs" ON public.event_rsvps;
DROP POLICY IF EXISTS "Public can delete RSVPs" ON public.event_rsvps;

CREATE POLICY "Public RSVPs are viewable by everyone"
  ON public.event_rsvps FOR SELECT
  USING (true);

CREATE POLICY "Public can insert RSVPs"
  ON public.event_rsvps FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Authenticated can delete RSVPs"
  ON public.event_rsvps FOR DELETE
  USING (auth.role() = 'authenticated');

-- =============================================
-- PARTE 9: POLICIES - AUDIO PILLOLE
-- =============================================

DROP POLICY IF EXISTS "Allow public read access on audio_pillole" ON public.audio_pillole;
DROP POLICY IF EXISTS "Allow authenticated insert on audio_pillole" ON public.audio_pillole;
DROP POLICY IF EXISTS "Allow authenticated update on audio_pillole" ON public.audio_pillole;
DROP POLICY IF EXISTS "Allow authenticated delete on audio_pillole" ON public.audio_pillole;

CREATE POLICY "Allow public read access on audio_pillole"
  ON public.audio_pillole FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow authenticated insert on audio_pillole"
  ON public.audio_pillole FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated update on audio_pillole"
  ON public.audio_pillole FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated delete on audio_pillole"
  ON public.audio_pillole FOR DELETE
  TO authenticated
  USING (true);

-- =============================================
-- PARTE 10: POLICIES - PRESS (Rassegna Stampa)
-- =============================================

DROP POLICY IF EXISTS "Allow public read access on press" ON public.press;
DROP POLICY IF EXISTS "Allow authenticated insert on press" ON public.press;
DROP POLICY IF EXISTS "Allow authenticated update on press" ON public.press;
DROP POLICY IF EXISTS "Allow authenticated delete on press" ON public.press;

CREATE POLICY "Allow public read access on press"
  ON public.press FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow authenticated insert on press"
  ON public.press FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated update on press"
  ON public.press FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated delete on press"
  ON public.press FOR DELETE
  TO authenticated
  USING (true);

-- =============================================
-- PARTE 11: STORAGE BUCKETS
-- =============================================
-- NOTA: I bucket devono essere creati manualmente dalla Dashboard
-- Vai su Storage > New Bucket e crea:
--   1. "images" - Public = true
--   2. "audio" - Public = true  
-- (Il bucket "press" non serve più, usiamo Cloudflare R2)

-- Storage Bucket per immagini (se non esiste)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Bucket per audio
INSERT INTO storage.buckets (id, name, public) 
VALUES ('audio', 'audio', true)
ON CONFLICT (id) DO NOTHING;

-- =============================================
-- PARTE 12: POLICIES STORAGE
-- =============================================

-- Policies per bucket "images"
DROP POLICY IF EXISTS "Public Access images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated upload images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated update images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated delete images" ON storage.objects;

CREATE POLICY "Public Access images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'images');

CREATE POLICY "Authenticated upload images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'images' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated update images"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'images' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated delete images"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'images' AND auth.role() = 'authenticated');

-- Policies per bucket "audio"
CREATE POLICY "Public Access audio"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'audio');

CREATE POLICY "Authenticated upload audio"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'audio' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated delete audio"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'audio' AND auth.role() = 'authenticated');

-- =============================================
-- FINE SCHEMA
-- =============================================

-- Per verificare che tutto sia stato creato:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
