-- Gallery CMS (run on existing databases)
CREATE TABLE IF NOT EXISTS public.gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  image_url TEXT NOT NULL,
  alt TEXT NOT NULL DEFAULT '',
  caption TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_published BOOLEAN NOT NULL DEFAULT true,
  source_filename TEXT UNIQUE
);

CREATE INDEX IF NOT EXISTS gallery_images_public_idx
  ON public.gallery_images (is_published, display_order);
