-- =============================================
-- SERGIO CONTEGIACOMO - Schema Postgres VPS
-- (senza Supabase Auth / Storage / RLS)
-- =============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Articles (Blog)
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  published_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  author TEXT,
  cover_image TEXT,
  excerpt TEXT,
  content TEXT,
  tags TEXT[]
);

-- Events
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  date TIMESTAMPTZ,
  time TEXT,
  location TEXT,
  cover_image TEXT,
  pdf_url TEXT,
  description TEXT,
  price TEXT,
  status TEXT CHECK (status IN ('upcoming', 'past')),
  tags TEXT[]
);

-- Comments
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  article_slug TEXT NOT NULL REFERENCES public.articles(slug) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  content TEXT NOT NULL
);

-- Event RSVPs
CREATE TABLE IF NOT EXISTS public.event_rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  event_slug TEXT NOT NULL REFERENCES public.events(slug) ON DELETE CASCADE,
  user_name TEXT,
  user_email TEXT,
  status TEXT CHECK (status IN ('attending', 'not_attending'))
);

-- AudioPillole
CREATE TABLE IF NOT EXISTS public.audio_pillole (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  duration TEXT,
  published_at DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Press (Rassegna Stampa)
CREATE TABLE IF NOT EXISTS public.press (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  testata TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  published_at DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Podcasts
CREATE TABLE IF NOT EXISTS public.podcasts (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  duration TEXT,
  episode_number INTEGER,
  is_published BOOLEAN NOT NULL DEFAULT true,
  published_at DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Testimonials
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  author_name TEXT NOT NULL,
  author_role TEXT,
  quote TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  is_published BOOLEAN DEFAULT false,
  featured BOOLEAN DEFAULT false,
  display_order INTEGER DEFAULT 0
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_articles_slug ON public.articles(slug);
CREATE INDEX IF NOT EXISTS idx_articles_published_at ON public.articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_slug ON public.events(slug);
CREATE INDEX IF NOT EXISTS idx_events_date ON public.events(date DESC);
CREATE INDEX IF NOT EXISTS idx_comments_article_slug ON public.comments(article_slug);
CREATE INDEX IF NOT EXISTS idx_event_rsvps_event_slug ON public.event_rsvps(event_slug);
CREATE INDEX IF NOT EXISTS idx_audio_pillole_published_at ON public.audio_pillole(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_press_published_at ON public.press(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_podcasts_published_at ON public.podcasts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_podcasts_published ON public.podcasts(is_published, episode_number);
CREATE INDEX IF NOT EXISTS testimonials_published_idx ON public.testimonials(is_published, display_order);
CREATE INDEX IF NOT EXISTS testimonials_featured_idx ON public.testimonials(featured);

-- Views
CREATE OR REPLACE VIEW public.article_stats AS
SELECT
  article_slug,
  COUNT(*) AS comment_count,
  AVG(rating)::NUMERIC(3,2) AS average_rating
FROM public.comments
GROUP BY article_slug;

CREATE OR REPLACE VIEW public.event_stats AS
SELECT
  event_slug,
  COUNT(*) FILTER (WHERE status = 'attending') AS attending_count,
  COUNT(*) FILTER (WHERE status = 'not_attending') AS not_attending_count
FROM public.event_rsvps
GROUP BY event_slug;

-- Testimonials updated_at trigger
CREATE OR REPLACE FUNCTION update_testimonials_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS testimonials_updated_at ON public.testimonials;
CREATE TRIGGER testimonials_updated_at
  BEFORE UPDATE ON public.testimonials
  FOR EACH ROW
  EXECUTE PROCEDURE update_testimonials_updated_at();
